version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: dataxm_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dataxm
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  dataxm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_code:/app

    container_name: dataxm_back
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dataxm?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8081

volumes:
  mysql_data:
  app_code:
